# Generated by Django 4.2.1 on 2023-06-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizcreate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
    ]
